### ISSUE TITLE
Not adding a final new line at the end of an included file may prevent compilation

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#27] opened 2022-08-30 17:22 UTC
In my main file main.asm, I include a file:
`include "macros.asm"`

The macros.asm file itself includes other files:
```
include "macros/video.asm"
include "macros/sound.asm"
```
If I don't add a new line at the end of the macros.asm file, compilation fails:
```
Pre-processing [./src/main.asm]
Error: [.\src\macros.asm:2] invalid char ';' (59) char 1
```

**Comment by EdouardBERGE** [comment] 2022-08-30 17:38
i cannot reproduce the bug, do you use windows or linux? (or...)

**Comment by anrikun** [comment] 2022-08-30 20:30
I'm using Windows.

**Comment by EdouardBERGE** [comment] 2022-09-03 06:17
Hi, i tried with 3 files, each of them without final CR, i did not reproduce the bug, can you send me a proper test-case?

**Comment by anrikun** [comment] 2022-09-06 16:35
Sorry for the late answer. For some reason I wasn't notified of your update.
[macro1.txt](https://github.com/EdouardBERGE/rasm/files/9498937/macro1.txt)
[macro2.txt](https://github.com/EdouardBERGE/rasm/files/9498938/macro2.txt)
[main2.txt](https://github.com/EdouardBERGE/rasm/files/9498939/main2.txt)
Try these 3 files (change .txt to .asm) and compile main2.asm

**Comment by EdouardBERGE** [comment] 2022-09-07 09:06
fixed with last commit
https://github.com/EdouardBERGE/rasm/commit/97ac8fd5eed04542b262c26db2f86ad7fc6f5a3b

**Closed by EdouardBERGE** 2022-09-07 09:06 UTC
